title: IT Abyss Wiki

author: Yulin Liang(梁煜麟)
description: Make coding more interesting
avatar: https://i.loli.net/2020/12/09/liWow1fZmFVJEYO.jpg
url: https://yulinliang.com
subtitle: try to make life better

menus: 
  主页: / || fa fa-home
  标签: /tags || fa fa-tags
  分类: /categories || fa fa-inbox
  归档: /archive || fa fa-archive
  关于: /about || fa fa-user

menu_icons:
  主页: images/home.svg
  标签: images/tags.svg
  分类: images/categories.svg
  归档: images/archive.svg
  关于: images/profile.svg  

leftBackground: https://i.loli.net/2020/12/09/C79FTYjh31ibdNZ.jpg

links:
  github: https://github.com/yulin-liang
  linkedin: https://www.linkedin.com/in/yulinliang/
  weibo: ylliangsysu@gmail.com
  rss: www.google.com

# 标签云
enable_tag_cloud: true


# 首页摘要展示
auto_excerpt:
  enable: true
  length: 150

# gitalk
enable_gitalk: false
gitalk_clientID: xxx
gitalk_clientSecret: xxx
gitalk_repo: yulin-liang.github.io
gitalk_owner: yulin-liang
gitalk_admin: yulin-liang
# 是否启用评论框的全屏遮罩效果
gitalk_distractionFreeMode: false